### ISSUE TITLE
up/down buttons are not generated with proper height if input element is detached/hidden

### ISSUE THREAD

**Issue by bwalex** [jonstipe/number-polyfill#18]
When the input type=number element that it is applied to is currently detached (e.g. when using Backbone to generate some DOM and then attach it) or when it is hidden, the wrong height is detected/used for the up/down buttons.

**Comment by jonstipe** [comment]
It now throws an error in these cases. We need to be able to measure the element's height. Attach the element to the DOM, THEN run the polyfill on it.
