### ISSUE TITLE
Can not put comma(.) using mozilla browser

### ISSUE THREAD

**Issue by jeffreyflukman** [jonstipe/number-polyfill#19]
I was trying to use input with number type for decimal number input.
It works great in chrome browser, but I can't input comma (with .) when I use input number in mozilla browser. And I thought it's a number-polyfill bug.

Thank you for your attention.

**Comment by jeffreyflukman** [comment]
I have fix this problem by adding _ref1 !== 46 in evt.which if part inside numberPolyfill.elemKeypressHandler function.

Here is the code : 

numberPolyfill.elemKeypressHandler = function(evt) {
        var p, _ref, _ref1;
        p = evt.data.p;
        if (evt.keyCode === 38) {
          p.increment();
        } else if (evt.keyCode === 40) {
          p.decrement();
        } else if (((_ref = evt.keyCode) !== 8 && _ref !== 9 && _ref !== 35 && _ref !== 36 && _ref !== 37 && _ref !== 39 && _ref !== 46) && ((_ref1 = evt.which) !== 45 && _ref1 !== 46 && _ref1 !== 48 && _ref1 !== 49 && _ref1 !== 50 && _ref1 !== 51 && _ref1 !== 52 && _ref1 !== 53 && _ref1 !== 54 && _ref1 !== 55 && _ref1 !== 56 && _ref1 !== 57)) {
          evt.preventDefault();
        }
      };

**Comment by jeffreyflukman** [comment]
I have not commit this bug fixed to number polyfill, so I reopen the issue.

**Comment by Squal38** [comment]
Hi Jeffrey,
I'm using your polyfill for one of my project and really need this fix. Would it be possible to do the required commit please ?

Cheers

**Comment by jeffreyflukman** [comment]
@Squal38 : you just need to find this "numberPolyfill.elemKeypressHandler = function(evt)" inside the number-polyfill.js and replace the function content with :

var p, ref, _ref1;
p = evt.data.p;
if (evt.keyCode === 38) {
p.increment();
} else if (evt.keyCode === 40) {
p.decrement();
} else if (((ref = evt.keyCode) !== 8 && ref !== 9 && _ref !== 35 && _ref !== 36 && _ref !== 37 && _ref !== 39 && _ref !== 46) && ((ref1 = evt.which) !== 45 && _ref1 !== 46 && _ref1 !== 48 && _ref1 !== 49 && _ref1 !== 50 && _ref1 !== 51 && _ref1 !== 52 && _ref1 !== 53 && _ref1 !== 54 && _ref1 !== 55 && _ref1 !== 56 && _ref1 !== 57)) {
evt.preventDefault();
}

That's it..

**Comment by Squal38** [comment]
Yes, but for now I include the polyfill with node.js directly from the Git repo. If I apply the patch manually, I will break this.
Any chance you do an update soon ? :-)

**Comment by jonstipe** [comment]
Finally found time to work on this. Fixed.

**Comment by jeffreyflukman** [comment]
+1

**Comment by Squal38** [comment]
Great !! Thanks a lot :-)
