### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by sindresorhus** [jonstipe/number-polyfill#4]
Hi, some suggestions:
- Mirror the master branch to a `gh-pages` branch to get a live demo of the plugin. Link to it from the readme. Most people won't bother downloading it to try it out.
- Update the demo html to also show how it looks for browsers that do support the number input.
- Add a repo description
- Add a link to caniuse in the readme: http://caniuse.com/#feat=input-number

**Comment by jonstipe** [comment]
All done.
